---
version: "3.7"
services:

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: ${NAMESPACE}-selenium
    ports:
    - 4444:4444
    volumes:
    - /dev/shm:/dev/shm
    networks:
    - internal
    - web
    restart: unless-stopped

  tor-haproxy:
    restart: always
    container_name: ${NAMESPACE}-tor-haproxy
    image: lucmichalski/tor-haproxy:latest
    build:
      context: .docker/tor-haproxy
      dockerfile: Dockerfile
    environment:
    - privoxy=1
    - privoxy_port=8119
    - tors=50
    networks:
    - internal
    - web
    ports:
    - 5566:5566
    - 2090:2090
    - 8119:8119
